# Authored by Jennifer Green
# jmgree17@ncsu.edu

Vagrant.configure(2) do |config|
  # Vagrant box
  config.vm.box = "box-cutter/ubuntu1404-desktop"
  
  # Vagrant hostname
  config.vm.hostname = "Vagrant-jmgree17-JITTAC"

  # Vagrant Provider Settings
   config.vm.provider "virtualbox" do |vb|
     vb.gui = true
	 vb.name = "Vagrant-jmgree17-JITTAC"
     vb.memory = "2048"
   end

  # Vagrant Provisioning
  config.vm.provision "shell", inline: <<-SHELL
	# Remove desktop Lock
	echo "***** Removing Desktop Lock *****"
	sudo gsettings set org.gnome.desktop.screensaver lock-enabled false
	
	# Install Java
	echo "***** Installing Java *****"
	sudo apt-get update
	sudo apt-get install -y openjdk-7-jdk
	
	# Install Adobe Flash Player plugin
	echo "***** Installing Flash *****"
	sudo apt-get install -y flashplugin-installer
	 
	# Install Eclipse
	echo "***** Downloading Eclipse *****"
	sudo wget "https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-JITTAC/raw/master/build-vm/vm-files/eclipse-indigo-noPlugins.tar.gz" -O /home/vagrant/Documents/eclipse.tar.gz
	sudo tar -xvf /home/vagrant/Documents/eclipse.tar.gz -C /home/vagrant/Documents/
	sudo rm /home/vagrant/Documents/eclipse.tar.gz	
	sudo chown -R vagrant "/home/vagrant/Documents/eclipse"
	
	# Install Plugins1 folder
	echo "***** Downloading Plugins For Eclipse. This may take several minutes.... *****"
	sudo wget "https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-JITTAC/raw/master/build-vm/vm-files/eclipse-plugins1.tar.gz" -O /home/vagrant/Documents/plugins1.tar.gz
	sudo tar -xvf /home/vagrant/Documents/plugins1.tar.gz -C /home/vagrant/Documents/
	sudo rm /home/vagrant/Documents/plugins1.tar.gz
	sudo chown -R vagrant "/home/vagrant/Documents/plugins1"
	sudo cp -R /home/vagrant/Documents/plugins1/plugins /home/vagrant/Documents/eclipse
	sudo rm -rf /home/vagrant/Documents/plugins1
	
	# Install Plugins2 folder
	sudo wget "https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-JITTAC/raw/master/build-vm/vm-files/eclipse-plugins2.tar.gz" -O /home/vagrant/Documents/plugins2.tar.gz
	sudo tar -xvf /home/vagrant/Documents/plugins2.tar.gz -C /home/vagrant/Documents/
	sudo rm /home/vagrant/Documents/plugins2.tar.gz
	sudo chown -R vagrant "/home/vagrant/Documents/plugins2"
	sudo cp -R /home/vagrant/Documents/plugins2/plugins /home/vagrant/Documents/eclipse
	sudo rm -rf /home/vagrant/Documents/plugins2
	sudo chown -R vagrant "/home/vagrant/Documents/eclipse/plugins"
	sudo chmod -R a+rwx "/home/vagrant/Documents/eclipse/plugins"
	
	# Get Workspace
	echo "***** Downloading Workspace with sample project *****"
	sudo wget "https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-JITTAC/raw/master/build-vm/vm-files/eclipse-workspace.tar.gz" -O /home/vagrant/Documents/workspace.tar.gz
	sudo tar -xvf /home/vagrant/Documents/workspace.tar.gz -C /home/vagrant/Documents/
	sudo rm /home/vagrant/Documents/workspace.tar.gz
	sudo chown -R vagrant "/home/vagrant/Documents/workspace"
	sudo chmod -R a+rwx "/home/vagrant/Documents/workspace"

	# Put Binary folder on desktop
	echo "***** Fetching binaries *****"
	sudo mkdir "/home/vagrant/Desktop/JITTAC Jars"
	sudo wget -O "/home/vagrant/Desktop/JITTAC Jars/net.sourceforge.actool.jdt_0.3.1.jar" https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-JITTAC/raw/master/binaries/net.sourceforge.actool.jdt_0.3.1.jar
	sudo wget -O "/home/vagrant/Desktop/JITTAC Jars/net.sourceforge.actool_0.3.1.jar" https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-JITTAC/raw/master/binaries/net.sourceforge.actool_0.3.1.jar
	sudo chown -R vagrant "/home/vagrant/Desktop/JITTAC Jars"
	
	# Put Icons on Desktop
	echo "***** Fetching Files for desktop *****"
	sudo ln -s /home/vagrant/Documents/eclipse/eclipse /home/vagrant/Desktop/Eclipse_link
	sudo wget -O "/home/vagrant/Desktop/Installation.txt" https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-JITTAC/raw/master/build-vm/vm-files/Installation.txt
	sudo wget -O "/home/vagrant/Desktop/Readme.txt" https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-JITTAC/raw/master/build-vm/vm-files/Readme.txt
	sudo wget -O "/home/vagrant/Desktop/JITTAC - YouTube.desktop" https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-JITTAC/raw/master/build-vm/vm-files/JITTACfinal%20-%20YouTube.desktop
	sudo wget -O "/home/vagrant/Desktop/license.txt" https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-JITTAC/raw/master/build-vm/vm-files/license.txt
	sudo chown -R vagrant "/home/vagrant/Desktop/Installation.txt"
	sudo chown -R vagrant "/home/vagrant/Desktop/Readme.txt"
	sudo chown -R vagrant "/home/vagrant/Desktop/JITTAC - YouTube.desktop"
	sudo chown -R vagrant "/home/vagrant/Desktop/license.txt"
	
	# Adding eclipse to autostart folder
	echo "***** Adding eclipse to autostart folder *****"
	sudo wget -O "/home/vagrant/Downloads/eclipse.desktop" https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-JITTAC/raw/master/build-vm/vm-files/eclipse.desktop
	sudo chown -R vagrant "/home/vagrant/Downloads/eclipse.desktop"
	sudo mkdir "/home/vagrant/.config/autostart/"
	sudo chown -R vagrant "/home/vagrant/.config/autostart/"
	sudo cp /home/vagrant/Downloads/eclipse.desktop "/home/vagrant/.config/autostart/"
	sudo chown -R vagrant "/home/vagrant/.config/autostart/eclipse.desktop"
	sudo rm /home/vagrant/Downloads/eclipse.desktop
	
	# Sidebar cleanup and logout
	echo "***** Removing Unneeded icons *****"
	sudo rm -f "/usr/share/applications/ubuntu-amazon-default.desktop"
	sudo rm -f "/usr/share/applications/libreoffice-calc.desktop"
	sudo rm -f "/usr/share/applications/libreoffice-writer.desktop"
	sudo rm -f "/usr/share/applications/libreoffice-impress.desktop"
	sudo rm -f "/usr/share/applications/ubuntu-software-center.desktop"
		
	# Empty Trash bin for VM size
	echo "***** Cleaning up trash *****"
	sudo rm -rf ~/.local/share/Trash/*
	
	# Finally Reboot for changes
	echo "***** Reboot required. Please stand by..... *****"
	sudo reboot
   SHELL
end
